import React from "react";
import { Container, Row, Col } from "react-bootstrap";

export default function Home () {
  
    return (
      <div>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, maximum-scale=1" />
        <title>Touching Pitch</title>
        <link rel="icon" href="william cheng copy.png" type="image/png" />
        <link href="css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <link href="css/font-awesome.css" rel="stylesheet" type="text/css" /> 
        <link href="css/animate.css" rel="stylesheet" type="text/css" />
        {/*[if lt IE 9]>
    
    
    
<![endif]*/}
        {/*Header_section*/}
        <header id="header_wrapper">
          <div className="container">
            <div className="header_box">
              {/* <div class="logo"><a href="#"><img src="img/logo.png" alt="logo"></a></div> */}
              {/* <nav className="navbar navbar-inverse" role="navigation">
                <div id="main-nav" className="collapse navbar-collapse navStyle">
                  <ul className="nav navbar-nav" id="mainNav">
                    <li className="active"><a href="#hero_section" className="scroll-link">Touching Pitch</a></li>
                    <li><a href="/albums" className="scroll-link">Albums</a></li>
                    <li><a href="Team.html" className="scroll-link">The Team</a></li>
                    <li><a href="cipher/cipher.html" className="scroll-link">Cipher</a></li>
                    <li><a href="Streams.html" className="scroll-link">Live Streams</a></li>
                  </ul>
                </div>
              </nav> */}
            </div>
          </div>
        </header>
        {/*Header_section*/} 
        {/*Hero_Section*/}
        <section id="hero_section" className="top_cont_outer">
          <div className="hero_wrapper">
            <div className="container">
              <div className="hero_section">
                <div className="row">
                  <div className="col-md-12">
                    <div className="top_left_cont">
                      <div id="andrew" />
                      <div id="grace" />
                      <div id="peggy" />
                      <div id="conan" />
                      <div id="sky" />
                      <div id="william" />
                    </div>
                  </div> 
                </div>
              </div>
            </div>
          </div>
        </section>
        {/*Hero_Section*/} 
        <section id="AlbumsAndCyphers">
          <div className="inner_wrapper aboutUs-container fadeInLeft animated wow delay-02s">
            <div className="container">
              <center>
                {/*<div class="inner_section">*/}
                {/*video_embedding*/}
                <br /><br />
                <br /><br />
                <h2 style={{color: 'white'}}>About the Project</h2>
                <h3 style={{color: 'white'}}>ALBUMS AND CYPHERS </h3>
                <h6 style={{}}>Across three ordinary Saturdays in October 2022, I set out to record three albums of free improvisations inspired by musical cyphers generated by the names of new acquaintances – some people I had just met around early September upon beginning a year of research fellowship. Their names are the point and also make part of a larger point, the point of making music in honor of / inspired by / as gift to others in the world, and why we might make a point of doing this when possible.  
                  The albums are (with placeholder titles) <br /><br />
                  i. playing around and thinking out loud [8 tracks rec. ~2:00-3:00pm EDT on Oct. 8, 2022]<br /> 
                  ii. pardon the ums [8 tracks rec. ~2:00-3:00pm EDT on Oct. 22, 2022]<br />
                  iii. soundworlds loading [8 tracks rec. ~3:00-4:30pm EDT on Oct. 29, 2022]<br /> <br />
                  Each album begins with a BENEDICTION – a leisurely warm-up, an improvisation on some melody I love, a (secular) blessing of what follows.
                  Each subsequent track of an album is an improvisation on a melody mapped onto the sequential letters in a person’s first name. <br /> <br />
                  (the note) A = (the letter) A, B = B, C = C ... G = G, H = A, I = B ... Y = D, Z = E <br /> <br />
                  Nominal musical cyphering was something many 19th-century European composers enjoyed playing around with. What I find heartening is how some composers seemed to take insouciant and self-humoring liberties when it came to their pieces based on cryptograms – that is, either by slightly fudging (or inventively justifying) letter-to-pitch conversions (maybe P equals D-flat just this once...) or by dropping letters from names entirely. After all, this name-inspired music is just – reminds us that much music is just – music that wouldn’t exist whatsoever if it weren’t for the oblique existence of someone else in the world. Music as spontaneous and unconditional gift, gratitude, a repository of communing, a potentialization toward being with.
                </h6>
                <center>
                  {/*</div>*/}
                </center></center></div>
          </div> 
        </section>
        <section id="BriefNotesonPractice">
          <div className="inner_wrapper aboutUs-container fadeInLeft animated wow delay-02s">
            <div className="container">
              <center>
                {/*<div class="inner_section">*/}
                {/*video_embedding*/}
                <h3 style={{color: 'white'}}> BRIEF NOTES ON PRACTICE, PAUSE </h3>
                <h6 style={{}}>I recently revived my improvisation practice in Spring 2022, ten years after the last time I gave a formal piano recital. Chronic pain resulting from a rare medical condition – an experience about which I have written openly elsewhere – was the main reason for the hiatus. <br /> <br />
                  These recordings from October 2022 are a burst of unedited snapshots of the way I am improvising now. My way of playing has changed since 2012, and I expect it will continue to change, as I do. <br /><br />
                  Aside from scribbling down the musical cyphers on staff notation (and occasionally jotting down extra ideas and melodic prolongations), I undertook each album recording session with minimal forethought. I allowed myself ~60-90 minutes to record each album. <br /><br />
                </h6>
                <center>
                  {/*</div>*/}
                </center></center></div>
          </div> 
        </section>
        <section id="AbouttheLargerProject">
          <div className="inner_wrapper aboutUs-container fadeInLeft animated wow delay-02s">
            <div className="container">
              <center>
                {/*<div class="inner_section">*/}
                {/*video_embedding*/}
                <h3 style={{color: 'white'}}> ABOUT THE LARGER PROJECT </h3>
                <h6 style={{}}>Equal parts memoir-treatise, live-recorded album, and VN-RPG (visual novel role-playing video game), TOUCHING PITCH illustrates how culturally hybridized pedagogies and practices of Western classical improvisation (a so-called lost art) can empower musicians to animate a spectrum of anti-racist, anti-assimilationist, and anti-capitalist agendas in the 21st century. <br /> <br />
                  In classical music spheres today – from conservatories and concert halls to nightclubs and YouTuber bedrooms – there are musicians who actively perform, teach, and advocate for improvisatory practices. But their numbers are few and far between, especially when held up against other musical traditions (such as jazz) where improvisers are legion, formative, and indispensable.   <br /> <br />
                  I contend it is disingenuous and unduly exculpatory to call improvisation a lost art in Western classical traditions. (For a modest summary of what tends to be included, excluded, and signified by Western art music today, please look forward to A Cultural History of Western Music in the Modern Age [ed. Cheng and Fosler-Lussier, forthcoming Bloomsbury 2023]). Things (e.g., the library book you need to return but can’t find) don’t just get lost – at least, not in this physical world where survival-minded and possession-and-territory-oriented humans reliably demonstrate reasons to optimize behaviors of keeping versus discarding things (and spaces and ideas). Over the last century of Western art music, free improvisatory practices have been consciously, keenly, systematically, bureaucratically, instrumentally, and institutionally suppressed and devalued by human agents, often those in positions of leadership or influence. Predictable but heretofore underexplored reasons for this fall of improvisation begin and end with some of the superbosses of late modernity: colonialism, racism, assimilationism, capitalism. <br /> <br />
                  Who has most benefited – financially, personally, professionally – from the suppression of improvisation? Who historically had (and who today has) incentives to curtail it? <br /> <br />
                  Who now has most potential to flourish from the revivification and repopularization of this practice? What if the answer is everyone? Can things change? Should they? <br /> <br />
                  How do the above questions connect and collide with the comparatively ample debates, practices, archives, and lived experiences around improvisation in jazz, oral and folk musics, and other improvisation-rich traditions and collectives?  <br /> <br />
                  I proceed with the belief that everyone can freely improvise in music – and that everyone can likely improvise more adventurously, beautifully, serendipitously, heart-forwardly, and playfully than they believe they can. Or the flipside: improvisation can be what we choose to call any act of doing adventurous, beautiful, serenditipous, heart-forward, and playful things with music, sound, bodies, voices, what have you (literally, whatever you have).<br /> <br />
                </h6>
                <center>
                  {/*</div>*/}
                </center></center></div>
          </div> 
        </section>
        <section id="AccessandProcess">
          <div className="inner_wrapper aboutUs-container fadeInLeft animated wow delay-02s">
            <div className="container">
              <center>
                {/*<div class="inner_section">*/}
                {/*video_embedding*/}
                <h3 style={{color: 'white'}}> ACCESS AND PROCESS </h3>
                <h6 style={{}}>The 24 tracks across these 3 albums will be interleaven with 26 rhizomatic prose chapters exploring personhood, temporality, ephemera, assimilation, perfectionism, grace, shame, genre, tradition, innovation, technology, capital, gift economies, scarcity, abundance, disability justice, and other topics and stories touched by improvisation. Listener will eventually have the option to access the totality of these recordings and writings as a standalone interactive VN-RPG (visual novel role-playing game) with choice-driven branching narratives and multiple endings. <br /> <br />
                  In this video game, even the smallest and seemingly banal choices may resonate with immediate or latent consequence. Will you build a virtual world where improvisation thrives, or one where it becomes outlawed by the ruling GOAT party (Gatekeepers of All Taste)? What do these mysterious GOATs – which are actual talking mountain goats with frightening telekinetic powers – want? Day to day, will you spend your limited practice room hours learning repertoire or inventing new licks? Will you spur factionalism among improvising communities, pitting the expansionist Add-Libs and bloodthirsty Vamps against one another in corporate-sponsored reality competitions? Will you found a for-profit conservatory and amass more power than you could ever have imagined? Will you survive? <br /> <br />
                  I am developing this multi-modal project in collaboration with the University of Michigan Press (host platform and release TBD) and with support from the Radcliffe Institute at Harvard University. <br /> <br />
                  In the 2022-23 academic year, I have the pleasure and privilege of working with five Radcliffe Research Partners. Their names are Andrew Gong, Conan Lu, Grace Kim, Peggy Yin, and Sky Jung.<br /> <br />
                  Project updates (dev diaries) will be rolled out as they come. Akin to improvisation, the process is sometimes the point, so it makes sense to show it. Please email williamcheng@gmail.com if you would like to receive updates. <br /> <br />
                  I am using SoundCloud only as a temporary host site for these private playlists.<br /> <br />
                </h6>
                <center>
                  {/*</div>*/}
                </center></center></div>
          </div> 
        </section>
        {/*Footer*/}
        {/*<footer class="footer_wrapper" id="contact">*/}
        <div className="container">
          <section className="page_section contact" id="contact">
            <div className="contact_section">
              <h2 style={{color: 'rgb(255, 255, 255)'}}>Contact form.</h2>
              <div className="row">
                <div className="col-lg-4">
                </div>
                <div className="col-lg-4">
                </div>
                <div className="col-lg-4">
                </div>
              </div>
            </div>
            <div className="row">
              <div className="col-lg-4 wow fadeInLeft">	
                <div className="contact_info">
                  <div className="detail">
                    <h4 style={{color: 'rgb(255, 255, 255)'}}>EMAIL US</h4>
                    {/*<p style = "color: black">EMAIL NOT FOUND</p>*/}
                    <p style={{color: 'white'}}>william.cheng@dartmouth.edu</p>
                  </div> 
                </div>
              </div>
              <div className="col-lg-8 wow fadeInLeft delay-06s">
                <center>
                  <div className="form">
                    <textarea className="input-text text-area" cols={0} rows={0} onfocus="if(this.value==this.defaultValue)this.value='';" onblur="if(this.value=='')this.value=this.defaultValue;" defaultValue={"MESSAGE"} />
                    <input className="input-btn" type="submit" defaultValue="send" onclick="myFunction()" />
                  </div>
                  <center>
                  </center></center></div>
            </div>
          </section>
        </div>
        {/*</footer>*/}
      </div>
    );
  }
;
